// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChunksColumns holds the columns for the "chunks" table.
	ChunksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "t", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "data", Type: field.TypeBytes},
	}
	// ChunksTable holds the schema information for the "chunks" table.
	ChunksTable = &schema.Table{
		Name:       "chunks",
		Columns:    ChunksColumns,
		PrimaryKey: []*schema.Column{ChunksColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChunksTable,
	}
)

func init() {
}
