// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"github.com/mxcd/chunking-engine/ent/chunk"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChunkCreate is the builder for creating a Chunk entity.
type ChunkCreate struct {
	config
	mutation *ChunkMutation
	hooks    []Hook
}

// SetT sets the "t" field.
func (cc *ChunkCreate) SetT(t time.Time) *ChunkCreate {
	cc.mutation.SetT(t)
	return cc
}

// SetName sets the "name" field.
func (cc *ChunkCreate) SetName(s string) *ChunkCreate {
	cc.mutation.SetName(s)
	return cc
}

// SetData sets the "data" field.
func (cc *ChunkCreate) SetData(b []byte) *ChunkCreate {
	cc.mutation.SetData(b)
	return cc
}

// Mutation returns the ChunkMutation object of the builder.
func (cc *ChunkCreate) Mutation() *ChunkMutation {
	return cc.mutation
}

// Save creates the Chunk in the database.
func (cc *ChunkCreate) Save(ctx context.Context) (*Chunk, error) {
	cc.defaults()
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *ChunkCreate) SaveX(ctx context.Context) *Chunk {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *ChunkCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *ChunkCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cc *ChunkCreate) defaults() {
	if _, ok := cc.mutation.Data(); !ok {
		v := chunk.DefaultData
		cc.mutation.SetData(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *ChunkCreate) check() error {
	if _, ok := cc.mutation.T(); !ok {
		return &ValidationError{Name: "t", err: errors.New(`ent: missing required field "Chunk.t"`)}
	}
	if _, ok := cc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Chunk.name"`)}
	}
	if _, ok := cc.mutation.Data(); !ok {
		return &ValidationError{Name: "data", err: errors.New(`ent: missing required field "Chunk.data"`)}
	}
	return nil
}

func (cc *ChunkCreate) sqlSave(ctx context.Context) (*Chunk, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *ChunkCreate) createSpec() (*Chunk, *sqlgraph.CreateSpec) {
	var (
		_node = &Chunk{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(chunk.Table, sqlgraph.NewFieldSpec(chunk.FieldID, field.TypeInt))
	)
	if value, ok := cc.mutation.T(); ok {
		_spec.SetField(chunk.FieldT, field.TypeTime, value)
		_node.T = value
	}
	if value, ok := cc.mutation.Name(); ok {
		_spec.SetField(chunk.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := cc.mutation.Data(); ok {
		_spec.SetField(chunk.FieldData, field.TypeBytes, value)
		_node.Data = value
	}
	return _node, _spec
}

// ChunkCreateBulk is the builder for creating many Chunk entities in bulk.
type ChunkCreateBulk struct {
	config
	err      error
	builders []*ChunkCreate
}

// Save creates the Chunk entities in the database.
func (ccb *ChunkCreateBulk) Save(ctx context.Context) ([]*Chunk, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Chunk, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChunkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *ChunkCreateBulk) SaveX(ctx context.Context) []*Chunk {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *ChunkCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *ChunkCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
