// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/mxcd/chunking-engine/ent/chunk"
	"github.com/mxcd/chunking-engine/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chunkFields := schema.Chunk{}.Fields()
	_ = chunkFields
	// chunkDescData is the schema descriptor for data field.
	chunkDescData := chunkFields[2].Descriptor()
	// chunk.DefaultData holds the default value on creation for the data field.
	chunk.DefaultData = chunkDescData.Default.([]byte)
}
